spring:
  application:
    name: academia-digital-validacao
  datasource:
    url: jdbc:postgresql://localhost:5432/academia_digital?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type: trace