spring.application.name=dio-spring-security-jwt-4

security.config.prefix=Bearer
#security.config.key=SECRET_KEY
security.config.key=4b8d6f9a2c1e7d5f3a9b8c6d1e2f4a7b9c3d6e8f1a5b7c9d2e4f6a8b1c3d5e7f
security.config.expiration=3600000

##H2 Database Connection Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
# url usada em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa
# definir que quer visualizar toda a operação de SQL existente na aplicação exibindo por um LOG
spring.jpa.show-sql= true
# determinar para o Spring que o H2 vai estar disponível a nível de console via web
spring.h2.console.enabled=true
